server:
  port: 8086

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tarigor/hotelgrodnoinn-config-server.git
          clone-on-start: true